### ISSUE TITLE
Danger to brick your SARA modem!

### ISSUE THREAD

**Issue by oe1gca** [Seeed-Studio/WioLTE_Cat_NB1_Arduino_Library#10]
You can easily brick your modem due to the really bad design of the u-blox SARA R410M!
Be aware of this info from u-blox:

u-blox System Integration manual:
> ⚠An abrupt removal of the VCCsupply during SARA-R4 seriesmodules normal operations may lead to an unrecoverable faulty state!

And unrecoverable in this regard means: it can't be re-flashed  - you can dispose it !

So, take care when switching of the board!

**Comment by petemyron** [comment]
What's the experience when this happens? I can write to the board (for example, the `Sample` sketch), but it seems to keep crashing when trying to power up the module:
```
17:30:42.622 -> [00;49m[00;49m00:00:00.228 [01;34mWARN modem.h:28:modem_setup() Powering on module...[00;49m[00;49m00:00:00.228 [01;34mWARN modem.h:23:modem_setup() Arduino setup() starting up
17:30:45.584 -> [00;49m[00;49m00:00:00.228 [01;34mWARN modem.h:28:modem_setup() Powering on module...[00;49m[00;49m00:00:00.228 [01;34mWARN modem.h:23:modem_setup() Arduino setup() starting up
...
17:31:24.666 -> [00;49m[00;49m00:0
```
