### ISSUE TITLE
PlatformIO support

### ISSUE THREAD

**Issue by Bmooij** [Seeed-Studio/WioLTE_Cat_NB1_Arduino_Library#2]
Hi,

I recently bought the "Wio LTE Cat M1/NB-IoT Tracker" and I wanted to used it with platformIO.
But unfortunately there is no support for it.
Is there a possibility to add support for platformIO?

Thank you!

**Comment by lanselambor** [comment]
@Bmooij Sorry we currently won't make this library fit platformIO, but you can develop base on STM32F4DISCOVERY on platformIO to drive Wio LTE board.

http://docs.platformio.org/en/latest/boards/ststm32/disco_f407vg.html

**Comment by Salzi** [comment]
@Bmooij did you manage to use platformIO for that board?

**Comment by Bmooij** [comment]
@Salzi ~~yes~~. 
Now reading it back. I didn't manage to make it work from platformio, I did manage to make it work with the STM32duino library. But couldn't get it running in on platformio.

You can try this to use the STM32duino platform:

From the File menu select Preferences

Find the Additional Board Manager URLs text box.
Add the line
https://raw.githubusercontent.com/Bmooij/BoardManagerFiles/master/STM32/package_stm_index.json

From the Tools menu, go down to Board submenu and select Board Manager...

Search for STM32 by Bmooij and click Install - select version 1.8.1 
If you only find STM32 by STMicroelectronics remove the original stm32duino url from the Board Managers URL list

Quit and restart the Arduino IDE.

Note: It has been some time that I worked on it. The pin names from this library are not ported and I'm not sure anymore if I made some pin changes. But basically it should work.

**Comment by Bmooij** [comment]
These are the settings that are required to make it work:

![verify_selections](https://user-images.githubusercontent.com/9463244/83412588-a86c5b80-a41a-11ea-82c0-3a211711a4bd.png)

**Comment by Salzi** [comment]
Thank you @Bmooij for the answer.
In the mean time I found also [this](https://github.com/masato-ka/platform-wiolte). Will give it a try as soon as the rest is working. Currently I'm fighting with the [serial console](https://forum.seeedstudio.com/t/wio-lte-usb-com-port-issue-input-output-error/252236) of the module.
