### ISSUE TITLE
Example Code on Wiki Calling Non-Existent Function

### ISSUE THREAD

**Issue by emilytouchingcomputers** [Seeed-Studio/WioLTE_Cat_NB1_Arduino_Library#4]
This was kind of frustrating to track down, so maybe it'll save someone elses time :)

The **[Arduino Example - Network RSSI](https://github.com/Seeed-Studio/WioLTE_Cat_NB1_Arduino_Library/wiki#arduino-example---network-rssi)** example on the wiki calls `ublox.Check_If_Power_On()` in the setup.  It's been changed to `ublox.isAlive()`

Thanks!

**Comment by lanselambor** [comment]
@invpdx thank you for your correction， have fixed that.
