### ISSUE TITLE
MQTT packet size is set to 100, how can i increase it??

### ISSUE THREAD

**Issue by atiq4rahman** [Seeed-Studio/WioLTE_Cat_NB1_Arduino_Library#5]
what if i make the following changes ??
In Header file increase the value of the MQTT_MAX_PACKET_LENGTH. ‘\Documents\Arduino\libraries\WioLTE_Cat_NB1_Arduino_Library-master\ublox_sara_r4_mqtt.h’ 
In Source file increase the txBuf, mqtt_packets, topic & msg size as per the requirement. 
‘\Documents\Arduino\libraries\WioLTE_Cat_NB1_Arduino_Library-master\ublox_sara_r4_mqtt.cpp’. 

Using inbuilt functions in header file to change the variables msg_length and len in order to change packet length field.
void setPublishHandler(void (*handler)(char *topic, const char *msg, size_t msg_length));
void setPacketHandler(void (*handler)(char *pckt, size_t len));

**Comment by g-berthiaume** [comment]
This seems to be a SARA-R4 limitation. 

See this question on the official ublox forum: [[SARA-R4] MQTT publish payload limit?
](https://portal.u-blox.com/s/question/0D52p00008v9QqYCAU/sarar4-mqtt-publish-payload-limit)
